name: {{project_name}}_navigator
description: "{{project_name}} mobile app"
publish_to: "none"
version: 0.0.1+1

environment: 
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  flutter_riverpod:
  go_router:

  # feature
  example:
    path: ../../feature/example

dev_dependencies:
  build_runner:
  go_router_builder:
  

flutter:
  uses-material-design: true