name: {{project_name}}_app
description: "{{project_name}} mobile app"
publish_to: "none"
version: 0.0.1+1

environment: 
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Dependencies
  flutter_riverpod:

  # Theme
  design_system:
    path: ../../core/design_system
  
  # Navigator
  {{project_name}}_navigator:
    path: ../{{project_name}}_navigator
  
  # Feature
  example:
    path: ../../feature/example

flutter:
  uses-material-design: true